# Generated by Django 3.0.10 on 2020-09-24 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_posted', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(db_index=True),
        ),
    ]
