# Generated by Django 3.0.10 on 2020-09-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
