# Generated by Django 3.0.10 on 2020-09-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_name'),
        ('relationships', '0002_auto_20200919_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('NONE', 'none'), ('SEND', 'send'), ('ACCEPTED', 'accepted')], default='NONE', max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('sender', 'receiver')},
        ),
    ]
