# Generated by Django 3.0.10 on 2020-09-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0003_auto_20200919_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('NONE', 'none'), ('SEND', 'send'), ('ACCEPTED', 'accepted')], max_length=8),
        ),
    ]
